spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.34:3306/campus?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  #redis配置
  redis:
    host: 192.168.8.33
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        min-idle: 0


mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #mybatis-plus日志
  configuration:
    #开启打印
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #关闭打印
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl